//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} row(s) returned과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatchListLoadedFormat {
            get {
                return ResourceManager.GetString("BatchListLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonInstallService {
            get {
                return ResourceManager.GetString("ButtonInstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Batch List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonLoadBatchList {
            get {
                return ResourceManager.GetString("ButtonLoadBatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonReload {
            get {
                return ResourceManager.GetString("ButtonReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonRestart {
            get {
                return ResourceManager.GetString("ButtonRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ButtonUninstallService {
            get {
                return ResourceManager.GetString("ButtonUninstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColumnDisplayName {
            get {
                return ResourceManager.GetString("ColumnDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColumnIsEnabled {
            get {
                return ResourceManager.GetString("ColumnIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColumnLastResult {
            get {
                return ResourceManager.GetString("ColumnLastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColumnLastRunAt {
            get {
                return ResourceManager.GetString("ColumnLastRunAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Procedure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColumnProcedureName {
            get {
                return ResourceManager.GetString("ColumnProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColumnSchedule {
            get {
                return ResourceManager.GetString("ColumnSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved Batches: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DatabaseBatchSizeText {
            get {
                return ResourceManager.GetString("DatabaseBatchSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create configuration files and folders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorConfigDirCreate {
            get {
                return ResourceManager.GetString("ErrorConfigDirCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read configuration file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorConfigFileRead {
            get {
                return ResourceManager.GetString("ErrorConfigFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write configuration file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorConfigFileWrite {
            get {
                return ResourceManager.GetString("ErrorConfigFileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decryption failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorDecryption {
            get {
                return ResourceManager.GetString("ErrorDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorEncryption {
            get {
                return ResourceManager.GetString("ErrorEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1-64 (default 4)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HintMaxConcurrency {
            get {
                return ResourceManager.GetString("HintMaxConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polling Interval Format (hh:mm:ss)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HintPollingIntervalFormat {
            get {
                return ResourceManager.GetString("HintPollingIntervalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelDatabase {
            get {
                return ResourceManager.GetString("LabelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Log Level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelDefaultLogLevel {
            get {
                return ResourceManager.GetString("LabelDefaultLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hosting Lifetime Log Level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelHostingLifetimeLogLevel {
            get {
                return ResourceManager.GetString("LabelHostingLifetimeLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integrated Security과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelIntegratedSecurity {
            get {
                return ResourceManager.GetString("LabelIntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Concurrent Batches과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelMaxConcurrency {
            get {
                return ResourceManager.GetString("LabelMaxConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polling Interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelPollingInterval {
            get {
                return ResourceManager.GetString("LabelPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Procedure Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelProcedureName {
            get {
                return ResourceManager.GetString("LabelProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelServer {
            get {
                return ResourceManager.GetString("LabelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelServiceStatus {
            get {
                return ResourceManager.GetString("LabelServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelUserId {
            get {
                return ResourceManager.GetString("LabelUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Critical과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogLevelCritical {
            get {
                return ResourceManager.GetString("LogLevelCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogLevelDebug {
            get {
                return ResourceManager.GetString("LogLevelDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogLevelError {
            get {
                return ResourceManager.GetString("LogLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogLevelInformation {
            get {
                return ResourceManager.GetString("LogLevelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogLevelTrace {
            get {
                return ResourceManager.GetString("LogLevelTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogLevelWarning {
            get {
                return ResourceManager.GetString("LogLevelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate Instance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageDuplicateInstance {
            get {
                return ResourceManager.GetString("MessageDuplicateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have administrator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageNotAdmin {
            get {
                return ResourceManager.GetString("MessageNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageReloadDone {
            get {
                return ResourceManager.GetString("MessageReloadDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageSaveFailed {
            get {
                return ResourceManager.GetString("MessageSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageSaveSuccess {
            get {
                return ResourceManager.GetString("MessageSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Worker will reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageWorkerWillReload {
            get {
                return ResourceManager.GetString("MessageWorkerWillReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResultFailure {
            get {
                return ResourceManager.GetString("ResultFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResultSuccess {
            get {
                return ResourceManager.GetString("ResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScheduleDailyFormat {
            get {
                return ResourceManager.GetString("ScheduleDailyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Every {0} hr과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScheduleEveryHoursFormat {
            get {
                return ResourceManager.GetString("ScheduleEveryHoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Every {0} min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScheduleEveryMinutesFormat {
            get {
                return ResourceManager.GetString("ScheduleEveryMinutesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Every {0} sec과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScheduleEverySecondsFormat {
            get {
                return ResourceManager.GetString("ScheduleEverySecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Every {0} month(s) {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScheduleMonthlyFormat {
            get {
                return ResourceManager.GetString("ScheduleMonthlyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScheduleUnknown {
            get {
                return ResourceManager.GetString("ScheduleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly {0} {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScheduleWeeklyFormat {
            get {
                return ResourceManager.GetString("ScheduleWeeklyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch service binary not found: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServiceBinaryNotFoundFormat {
            get {
                return ResourceManager.GetString("ServiceBinaryNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Runs scheduled batches defined in the BatchList table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SECUiDEA Batch Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServiceDisplayName {
            get {
                return ResourceManager.GetString("ServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install failed (exit {0}): {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServiceInstallFailedFormat {
            get {
                return ResourceManager.GetString("ServiceInstallFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstall failed (exit {0}): {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServiceUninstallFailedFormat {
            get {
                return ResourceManager.GetString("ServiceUninstallFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Denied과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusAccessDenied {
            get {
                return ResourceManager.GetString("StatusAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Installed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusNotInstalled {
            get {
                return ResourceManager.GetString("StatusNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Pending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusStartPending {
            get {
                return ResourceManager.GetString("StatusStartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Pending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusStopPending {
            get {
                return ResourceManager.GetString("StatusStopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TabBatch {
            get {
                return ResourceManager.GetString("TabBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TabDatabase {
            get {
                return ResourceManager.GetString("TabDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TabLogging {
            get {
                return ResourceManager.GetString("TabLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TabService {
            get {
                return ResourceManager.GetString("TabService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestFailed {
            get {
                return ResourceManager.GetString("TestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestSuccess {
            get {
                return ResourceManager.GetString("TestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleConfirm {
            get {
                return ResourceManager.GetString("TitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the correct database information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationDatabaseRequired {
            get {
                return ResourceManager.GetString("ValidationDatabaseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max concurrency must be an integer between 1 and 64과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationMaxConcurrencyRange {
            get {
                return ResourceManager.GetString("ValidationMaxConcurrencyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the correct password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check the interval Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationPollingIntervalFormat {
            get {
                return ResourceManager.GetString("ValidationPollingIntervalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the correct port number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationPortRange {
            get {
                return ResourceManager.GetString("ValidationPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check the procedure name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationProcedureNameRequired {
            get {
                return ResourceManager.GetString("ValidationProcedureNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the correct server information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationServerRequired {
            get {
                return ResourceManager.GetString("ValidationServerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the correct user id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationUserIdRequired {
            get {
                return ResourceManager.GetString("ValidationUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SECUiDEA Batch Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
