//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Saved Batches: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DatabaseBatchSizeText {
            get {
                return ResourceManager.GetString("DatabaseBatchSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create configuration files and folders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorConfigDirCreate {
            get {
                return ResourceManager.GetString("ErrorConfigDirCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read configuration file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorConfigFileRead {
            get {
                return ResourceManager.GetString("ErrorConfigFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write configuration file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorConfigFileWrite {
            get {
                return ResourceManager.GetString("ErrorConfigFileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decryption failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorDecryption {
            get {
                return ResourceManager.GetString("ErrorDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorEncryption {
            get {
                return ResourceManager.GetString("ErrorEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelDatabase {
            get {
                return ResourceManager.GetString("LabelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integrated Security과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelIntegratedSecurity {
            get {
                return ResourceManager.GetString("LabelIntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelServer {
            get {
                return ResourceManager.GetString("LabelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelUserId {
            get {
                return ResourceManager.GetString("LabelUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SECUiDEA Batch Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServiceDisplayName {
            get {
                return ResourceManager.GetString("ServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Denied과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusAccessDenied {
            get {
                return ResourceManager.GetString("StatusAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Installed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusNotInstalled {
            get {
                return ResourceManager.GetString("StatusNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Pending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusStartPending {
            get {
                return ResourceManager.GetString("StatusStartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Pending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusStopPending {
            get {
                return ResourceManager.GetString("StatusStopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestFailed {
            get {
                return ResourceManager.GetString("TestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestSuccess {
            get {
                return ResourceManager.GetString("TestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
